CPP=g++
INCLUDE=-I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libgtop-2.0
cpuinfo.o: cpuinfo.cpp
	$(CPP) $(INCLUDE) $< -o $@ -lgtop-2.0 -lglib-2.0

